const express = require('express')
const router = express.Router()
const addArt = require('./postArt')
const login = require('./logIn')
const getArt = require('./getArt')
const getArtist = require('./getArtist')
const signup = require('./signup')
const checkEmail = require('../middlewares/checkEmail')
const recentArt = require('./recentArt')
const artsForArtist = require('./artsForArtist')

router.get('/api/all-art-artist/:id', artsForArtist)
router.get('/api/get-art', getArt)
router.get('/api/artist/:id', getArtist)
router.post('/api/signup', checkEmail, signup)
router.post('/api/login', login)
router.post('/api/add-art', addArt)
router.get('/api/recent', recentArt)

module.exports = router
